configuration: Release

image: Visual Studio 2017

branches:
  only:
    - master

build:
  verbosity: minimal

deploy:
  tag: LatestCommit
  release: SaveStadium [Latest Commit]
  description: 'This build is updated every time a commit is pushed to the master branch.\n\nMessage: $(APPVEYOR_REPO_COMMIT_MESSAGE)\n\n Timestamp: $(APPVEYOR_REPO_COMMIT_TIMESTAMP)'
  provider: GitHub
  auth_token:
    secure: xauaTCyRR7zXmIIk4uXxttIa2s/DKhiMVYbGn6BMy/suM2ow6gUe0GNrnS+d1Q/q
  artifact: SaveStadium.zip
  draft: false
  prerelease: true
  force_update: true
  on:
    branch: master

after_build:
  - 7z a "SaveStadium.zip" "%APPVEYOR_BUILD_FOLDER%\SaveStadium\bin\Release\SaveStadium.exe"
  - 7z a "SaveStadium.zip" "%APPVEYOR_BUILD_FOLDER%\SaveStadium\bin\Release\SaveStadium.exe.config"
  - appveyor PushArtifact "SaveStadium.zip"
